services:
  postgres:
    image: postgres:15-alpine
    container_name: auth_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - auth_db_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_auth_db:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  auth_db_volume:
  redis_auth_db:

networks:
  auth_network:
    driver: bridge
