"""update table role_permission

Revision ID: 5c2e988d0019
Revises: 9ea147b08146
Create Date: 2025-10-18 11:00:42.930358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2e988d0019'
down_revision: Union[str, Sequence[str], None] = '9ea147b08146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    # ### end Alembic commands ###
