"""update tables

Revision ID: 9ea147b08146
Revises: e0789a2a7186
Create Date: 2025-10-18 08:53:00.395638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea147b08146'
down_revision: Union[str, Sequence[str], None] = 'e0789a2a7186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['name'])
    op.create_unique_constraint(None, 'permissions', ['permission_id'])
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'roles', ['role_id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
